[package]
name = "ditto-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ditto-artifact-store.workspace = true
ditto-capability-index.workspace = true
ditto-context-compiler.workspace = true
ditto-context-graph.workspace = true
ditto-event-store.workspace = true
ditto-model-driver.workspace = true
ditto-protocol.workspace = true
ditto-task-state.workspace = true
futures.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true

